### ISSUE TITLE
`JaroWinkler.c_distance` aborted

### ISSUE THREAD

**Issue by hanachin** [tonytonyjan/jaro_winkler#10]
Following code cause error in Ruby 2.2.3 and JaroWinkler 1.3.6

```rb
require 'jaro_winkler'

JaroWinkler.c_distance("In that case, you can set the `config.force_ssl` in your environment file.", "In this guide you will learn how controllers work and how they fit into the request cycle in your application.")
```

Reproduce code:
https://github.com/hanachin/jaro_winkler_sample
https://travis-ci.org/hanachin/jaro_winkler_sample

**Comment by tonytonyjan** [comment]
@hanachin I guess it's buffer issue, not verified yet.
https://github.com/tonytonyjan/jaro_winkler/blob/master/ext/jaro_winkler/jaro.h#L5

**Comment by hanachin** [comment]
@tonytonyjan thanks for quick response :+1:

**Comment by tonytonyjan** [comment]
BTW, since Jaro–Winkler distance is designed and best suited for short strings such as person names, that's why I define a small number as length limitation.

I wonder what kind of application are you building? Your sample strings are quite long.

**Comment by tonytonyjan** [comment]
BTW, since Jaro–Winkler distance is designed and best suited for short strings such as person names, that's why I define a small number as length limitation.

I wonder what kind of application are you building? Your sample strings are quite long.

**Comment by hanachin** [comment]
I'm finding translated sentences from sentences translated previously.

> BTW, since Jaro–Winkler distance is designed and best suited for short strings such as person names, that's why I define a small number as length limitation.

I missed that :see_no_evil: 
My application uses even more long strings, I should change the algorithm :stuck_out_tongue:

**Comment by tonytonyjan** [comment]
@hanachin I've merged your pull request, thanks for contribution. But I soon found a better way to do it. Because Variable-length automatic arrays are allowed in C99, we can easily [replace the macro with variable](https://github.com/tonytonyjan/jaro_winkler/commit/244c513c4a92b9ed64585fa0326ab5c43d284939#diff-30259c22f12391d5fda1033d9e2b1cd9L30).

cheers :beers:

**Comment by hanachin** [comment]
:beers: :hibiscus:
