### ISSUE TITLE
1.5.3 for JRuby

### ISSUE THREAD

**Issue by sfgeorge** [tonytonyjan/jaro_winkler#30]
Hello, I'm hitting the following `Could not find jaro_winkler-1.5.3-java in any of the sources` error on jruby-9.2.7.0.  It looks like a 1.5.3-java version just needs to be released.

![screenshot of build failure](https://user-images.githubusercontent.com/208529/61586635-ce5c7a80-ab3e-11e9-890d-2503c02a100b.png)

Thanks very much for your help.

**Comment by tonytonyjan** [comment]
According to https://rubygems.org/gems/jaro_winkler, v1.5.3 has been released in the last month.

<img width="271" alt="Screen Shot 2019-07-22 at 11 56 39 AM" src="https://user-images.githubusercontent.com/809410/61605386-c9e7ad00-ac77-11e9-9ded-2527fd8d5443.png">

The image your gave seems like log messages from a certain CI service. Maybe you can try to google using `"CI SERVICE NAME" "could not find" "in any of the sources"` as keywords to find the solution for this issue?

**Comment by sfgeorge** [comment]
Sounds good, closing.
