### ISSUE TITLE
InvalidWeightError question

### ISSUE THREAD

**Issue by IlyaOsotov** [tonytonyjan/jaro_winkler#37]
I want to know, why you raise an error when weight more than 0.25. If I fork it and change the value, are there some problems with it? I just see python algorithm by my colleagues and they don't have any issues with it.

**Comment by sabunt** [comment]
@tonytonyjan

**Comment by tonytonyjan** [comment]
Hi @sabunt,

The reason is that If the weight exceeds 0.25, the similarity would become larger than 1, which is not expected.

For detail, please check the formula in the Wiki page:

https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance#Jaro%E2%80%93Winkler_Similarity

**Comment by IlyaOsotov** [comment]
Hi @tonytonyjan,
Thanks for your quick response. Sorry for disturbing you.
