### ISSUE TITLE
Jaro-Winkler similarity?

### ISSUE THREAD

**Issue by kwerle** [tonytonyjan/jaro_winkler#42]
I hate to bring this up, but it looks like this is actually measuring the Jaro-Winkler similarity.

https://en.wikipedia.org/wiki/Jaro%E2%80%93Winkler_distance
> The lower the Jaro–Winkler distance for two strings is, the more similar the strings are. The score is normalized such that 0 means an exact match and 1 means there is no similarity. The Jaro–Winkler similarity is the inversion, (1 − Jaro–Winkler distance).

**Comment by wynksaiddestroy** [comment]
I think @kwerle is right here.
