### ISSUE TITLE
Build Failure with ruby 3.03 on Apple Silicon

### ISSUE THREAD

**Issue by TruePath** [tonytonyjan/jaro_winkler#47]
When I try to build the gem on my M1 laptop using ruby 3.03p157 I get a compile error.  Specifically, it fails with incompatible function pointer types.  I'm attaching the log of a debug run of sudo gem install

[gem_make.out](https://github.com/tonytonyjan/jaro_winkler/files/7823824/gem_make.out.txt)

**Comment by tonytonyjan** [comment]
Looks like your environment doesn't have `gmkdir`.

Would you try this solution and see if it would work? https://stackoverflow.com/a/38241778/1009442

**Comment by TruePath** [comment]
Gah, I'm an idiot.  Apparently I managed to disable coreutils when I installed gdu (go disk usage program) and I didn't notice it in the logs.  So sorry for wasting your time.  It builds fine now.

**Comment by tonytonyjan** [comment]
Glad I can help 😸 

I'll close the issue. Let me know if you have any problem about installation.
