### ISSUE TITLE
Regarding the Ractor safe implementation

### ISSUE THREAD

**Issue by pocari** [tonytonyjan/jaro_winkler#53]
I believe that the Ractor safe implementation that was added in [this pull request]( https://github.com/tonytonyjan/jaro_winkler/pull/44) has not been merged into the current master branch. Was it rejected for some reason after being reviewed? If there was any discussion or issue related to this, I would appreciate it if you could let me know.

**Comment by tonytonyjan** [comment]
It's not rejected and I can't remember why it is not it the main branch. Sorry, I might made the mistake without even knowing. I'll fix it today.

**Comment by tonytonyjan** [comment]
@pocari It's in the main branch now.

https://github.com/tonytonyjan/jaro_winkler/commit/240d42dfc4f7daf9f99d7b891f724a2d217cbc37

Thank you!

**Comment by pocari** [comment]
@tonytonyjan Tahnk you!
